import React, { useState, useEffect } from 'react';

import { getTotal, getTotalRowTotal } from '../../functions';

const RowThree = (props) => {
  const { zeroRowThree, twentyRowThree, thirtyRowThree, fortyRowThree } = props;
  const [rowTotal, setRowTotal] = useState('০');

  useEffect(() => {
    setRowTotal(
      getTotalRowTotal(
        zeroRowThree,
        twentyRowThree,
        thirtyRowThree,
        fortyRowThree
      )
    );
  }, [zeroRowThree, twentyRowThree, thirtyRowThree, fortyRowThree]);

  return (
    <tr className='rowthree'>
      <td>২</td>
      <td>
        {getTotal(
          zeroRowThree.a3,
          twentyRowThree.a3,
          thirtyRowThree.a3,
          fortyRowThree.a3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.b3,
          twentyRowThree.b3,
          thirtyRowThree.b3,
          fortyRowThree.b3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.c3,
          twentyRowThree.c3,
          thirtyRowThree.c3,
          fortyRowThree.c3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.d3,
          twentyRowThree.d3,
          thirtyRowThree.d3,
          fortyRowThree.d3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.e3,
          twentyRowThree.e3,
          thirtyRowThree.e3,
          fortyRowThree.e3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.f3,
          twentyRowThree.f3,
          thirtyRowThree.f3,
          fortyRowThree.f3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.g3,
          twentyRowThree.g3,
          thirtyRowThree.g3,
          fortyRowThree.g3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.h3,
          twentyRowThree.h3,
          thirtyRowThree.h3,
          fortyRowThree.h3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.i3,
          twentyRowThree.i3,
          thirtyRowThree.i3,
          fortyRowThree.i3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.j3,
          twentyRowThree.j3,
          thirtyRowThree.j3,
          fortyRowThree.j3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.k3,
          twentyRowThree.k3,
          thirtyRowThree.k3,
          fortyRowThree.k3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.l3,
          twentyRowThree.l3,
          thirtyRowThree.l3,
          fortyRowThree.l3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.m3,
          twentyRowThree.m3,
          thirtyRowThree.m3,
          fortyRowThree.m3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.n3,
          twentyRowThree.n3,
          thirtyRowThree.n3,
          fortyRowThree.n3
        )}
      </td>
      <td className='oneTotal'>{rowTotal}</td>
      <td>
        {getTotal(
          zeroRowThree.p3,
          twentyRowThree.p3,
          thirtyRowThree.p3,
          fortyRowThree.p3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.q3,
          twentyRowThree.q3,
          thirtyRowThree.q3,
          fortyRowThree.q3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.r3,
          twentyRowThree.r3,
          thirtyRowThree.r3,
          fortyRowThree.r3
        )}
      </td>
      <td>
        {getTotal(
          zeroRowThree.s3,
          twentyRowThree.s3,
          thirtyRowThree.s3,
          fortyRowThree.s3
        )}
      </td>
    </tr>
  );
};

export default RowThree;
